# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/111g4Y9gPHIAAj9kLa364qHwgfcbP3hWX
"""

# app.py
import streamlit as st
import numpy as np
import pickle

# Tải mô hình và scaler
model = pickle.load(open("logistic_asd_model.pkl", "rb"))
scaler = pickle.load(open("scaler.pkl", "rb"))

st.title("🔎 Ứng dụng Sàng Lọc Tự Kỷ (ASD)")

# Giao diện nhập thông tin
def nhap_du_lieu():
    st.header("📝 Vui lòng nhập thông tin:")
    scores = [st.slider(f"Câu hỏi A{i+1}", 0, 1, 0, help="0 = Không, 1 = Có") for i in range(10)]

    used_app_before = st.selectbox("Bạn đã từng sử dụng ứng dụng này chưa?", ["Chưa", "Rồi"])
    jundice = st.selectbox("Trẻ có bị vàng da sau sinh không?", ["Không", "Có"])
    austim = st.selectbox("Gia đình bạn có người từng bị tự kỷ không?", ["Không", "Có"])
    relation = st.selectbox("Bạn là ai đối với người được đánh giá?", ["Bố/mẹ", "Bản thân", "Người thân khác", "Khác"])
    age_desc = st.selectbox("Nhóm tuổi của người được đánh giá?", ["Dưới 18 tuổi", "Từ 18 tuổi trở lên"])

    # Chuyển dữ liệu về dạng số
    mapping = {'Không': 0, 'Có': 1, 'Chưa': 0, 'Rồi': 1}
    used_app_before = mapping[used_app_before]
    jundice = mapping[jundice]
    austim = mapping[austim]
    relation_map = {'Bản thân': 0, 'Bố/mẹ': 1, 'Người thân khác': 2, 'Khác': 3}
    age_desc_map = {'Dưới 18 tuổi': 0, 'Từ 18 tuổi trở lên': 1}

    input_data = scores + [used_app_before, jundice, relation_map[relation], austim, age_desc_map[age_desc]]
    return np.array(input_data).reshape(1, -1)

X_input = nhap_du_lieu()

if st.button("🔍 Dự đoán"):
    X_input_scaled = scaler.transform(X_input)
    result = model.predict(X_input_scaled)[0]
    if result == 1:
        st.error("⚠️ Bạn đang có dấu hiệu Tự Kỷ. Vui lòng tham khảo ý kiến bác sĩ chuyên khoa.")
    else:
        st.success("✅ Không có dấu hiệu Tự Kỷ rõ ràng.")




    # --- Gợi ý tiếp theo ---
    st.markdown("### 🧭 Gợi ý hành động tiếp theo:")
    if pred == 1:
        st.info("""
        🔹 Hãy liên hệ chuyên gia tâm lý hoặc cơ sở y tế để được tư vấn kỹ lưỡng hơn.
        🔹 Ghi chép lại các biểu hiện thường gặp trong cuộc sống hàng ngày.
        🔹 Có thể tham khảo các tài liệu về ASD từ WHO, CDC hoặc các trung tâm hỗ trợ trong nước.
        """)
    else:
        st.success("""
        ✅ Bạn có thể yên tâm ở thời điểm hiện tại.
        🔹 Việc phát triển kỹ năng xã hội và cảm xúc vẫn ổn.
        🔹 Nếu còn băn khoăn, bạn có thể trao đổi thêm với chuyên gia.
        """)

